#!/usr/bin/env python3
"""Regenerate the machine-readable transcripts of every specification under
provenance/Spec sheets/ into provenance/derived/, together with a README on
how to read them and a SOURCES.json manifest (source hashes, tool versions).

The derived files are copies of copyrighted documents in another form; they
are for local use only and must not be distributed (see README.md there)."""
import argparse
import hashlib
import json
import os
import platform
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# (output name, source file, converter, what it is)
SOURCES = [
    ("hwp5", "한글문서파일형식_5.0_revision1.3.pdf", "pdf2md.py",
     "HWP 5.0 binary format: storage layout, records, controls"),
    ("hwp-distribution", "한글문서파일형식_배포용문서_revision1.2.pdf", "pdf2md.py",
     "distribution (read-only) documents: ViewText encryption"),
    ("hwp-equation", "한글문서파일형식_수식_revision1.3.pdf", "pdf2md.py",
     "equation script language"),
    ("hwp-chart", "한글문서파일형식_차트_revision1.2.pdf", "pdf2md.py",
     "chart objects"),
    ("hwp3-hwpml", "한글문서파일형식3.0_HWPML_revision1.2.pdf", "pdf2md.py",
     "HWP 3.0 binary format and HWPML (the XML format preceding OWPML)"),
    ("owpml-ksx6101", "KS X 6101 OWPML.html", "owpml_html2md.py",
     "KS X 6101 OWPML (the .hwpx format), with its XSD annexes"),
]

README = """\
# Machine-readable specification transcripts

Everything in this directory is generated by `tools/spec/build.py` from the
files in `provenance/Spec sheets/`; do not edit by hand, regenerate instead:

    python3 tools/spec/build.py

**Not for distribution.** The ᄒᆞᆫ글 format documents may only be redistributed
as unmodified originals, and KS X 6101 is a copyrighted standard. These
transcripts are a working aid on the development machine; the directory is
git-ignored. When citing, cite the original document and its printed page or
clause number, which the transcripts carry.

`SOURCES.json` records the SHA-256 of every source file and the tool versions
used, so a transcript can be checked against the original it came from.

## Files

| name | source | covers |
|---|---|---|
{files}

Each PDF gives `<name>.md` (transcript), `<name>.json` (block model: headings,
paragraphs, tables with spans, captions, an index of headings/tables/figures)
and `<name>/pages/pNNN.png` (every page rendered). The HTML gives
`owpml-ksx6101.md`, `owpml-ksx6101.json`, `owpml-ksx6101/img/` (the page's
embedded images) and `owpml-ksx6101/xsd/` (the normative schema annexes B–H
as `.xsd` files, each checked to be well-formed XML).

## Reading the PDF transcripts

* `<!-- page N · printed M · <png> -->` starts each page: N is the PDF page
  (and PNG) number, M the page number printed in the footer. Running
  headers and footers are removed.
* Line breaks are the source's own and are never re-flowed: ᄒᆞᆫ글 breaks
  Korean lines between any two characters, so a word can be split over two
  lines. When searching, allow a newline anywhere (or join the `lines` of a
  paragraph in the JSON). Text is verbatim and not Markdown-escaped; read
  the `.md` as plain text.
* Headings are bold numbered lines (`3.2.1.` → `###`; Roman parts → `#`).
* Tables are rebuilt from the ruling lines. Without merged cells they are
  pipe tables; with merged cells they are HTML tables (cell text is
  HTML-escaped there). `<br>` is a line break inside a cell. A one-cell box
  becomes a `>` block quote. A table that runs over a page break is joined
  into one (marked by a comment), a repeated header row is dropped, and a row
  split by the page break is rejoined.
* `*표 N …*` / `*그림 N …*` are captions; `[image]` marks a raster image (see
  the page PNG). Vector drawings exist only in the PNGs; boxes drawn around a
  diagram can come out as odd little tables, so check the PNG when a table
  has no caption.
* Character fixes, and nothing else: the private-use glyph U+F53A, and the
  same glyph where it has no Unicode mapping at all, become ᄒᆞᆫ; the
  Wingdings bullet becomes ▪; table-of-contents dot leaders become ` … `.
* Lost in transcription: italics and other character styling (the spec
  uses italics for user-defined summary properties, for example), and
  rendered equations, which are images.

## Reading the KS X 6101 transcript

* Headings carry the clause number from the page (`7.2.1`, annexes `A`–`I`).
* The site's glossary pop-ups are replaced by the word they wrapped, and the
  "AI추천문서" lists of unrelated standards are removed.
* XML examples are fenced ```` ```xml ```` blocks. Part of the saved page had
  been re-serialised by an HTML parser: in the examples there, element and
  attribute names are lower-cased, straight quotes were added around the
  document's own curly quotes and self-closing tags were expanded. Those
  examples carry a note; trust the XSD annexes for exact names.
  `owpml-ksx6101.json` → `report.lowercased_names` lists the names affected.
* Symbol-font characters are mapped to Unicode. The one private-use
  character left (U+F06C) is the bullet character inside an example's
  `<hh:bullet char="…">` and is data.
* Image alt texts are all "formula"; that is the site's generic alt text.
"""


def sha256(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec-dir", default="provenance/Spec sheets")
    ap.add_argument("--out", default="provenance/derived")
    a = ap.parse_args()

    os.makedirs(a.out, exist_ok=True)
    manifest = {
        "generator": "tools/spec/build.py",
        "tools": {
            "python": platform.python_version(),
            "mutool": subprocess.run(["mutool", "-v"], capture_output=True, text=True).stderr.strip(),
        },
        "documents": [],
    }
    for name, src, conv, what in SOURCES:
        path = os.path.join(a.spec_dir, src)
        subprocess.run([sys.executable, "-I", os.path.join(HERE, conv), path, "--out", a.out, "--name", name],
                       check=True)
        with open(os.path.join(a.out, name + ".json"), encoding="utf-8") as fh:
            doc = json.load(fh)
        manifest["documents"].append({
            "name": name, "source": path, "sha256": sha256(path), "converter": "tools/spec/" + conv,
            "covers": what, "report": doc.get("report") or {"glyph_fixes": doc.get("glyph_fixes")},
        })
    with open(os.path.join(a.out, "SOURCES.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, ensure_ascii=False, indent=1)
    files = "\n".join(f"| `{n}` | `{s}` | {w} |" for n, s, _, w in SOURCES)
    with open(os.path.join(a.out, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(README.format(files=files))


if __name__ == "__main__":
    main()
